name = "dosirak"
main = "worker.js"
compatibility_date = "2025-09-01"

# 정적 파일(public/index.html) 서빙 — worker.js 에서 env.ASSETS 로 접근
[assets]
directory = "./public"
binding = "ASSETS"

# 클라우드 저장(KV) — 연결됨
[[kv_namespaces]]
binding = "DOSIRAK"
id = "db67e57a4d80495f84a074ff539d8cac"
